model_params:
  Image_patch_size:
  - 256
  - 256
  - 3
  Mask_patch_size:
  - 256
  - 256
  Batch_size: 16
  Number_of_classes: 2
  Learning_rate: 0.0001
  Optimizer: nadam
  Epochs: 500
  Loss: sdice_loss
  Scheduler: Cycliclearning_rate
